sudo: required
language: java
service: 
    - docker
addons:
    apt:
        packages:
            - docker-ce
before_install:
    - chmod +x travis-script.sh
    - chmod +x travis-after_success.sh
script:
    - ./travis-script.sh

after_success:
    - ./travis-after_success.sh