sudo: required
language: java
service: 
    - docker
addons:
    apt:
        packages:
            - docker-ce

script:
    - cd eureka
    - mvn clean install
    
after_success:
    - echo $PWD
    - docker login -u $DOCKERID -p $DOCKERPWD
    - export IMAGE_NAME=xyd93/ayuda-eureka
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME